name: Build snapshot & changes

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: write  # necessario per commit & push

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install pandas requests

      - name: Build snapshot from CSV
        env:
          CSV_URL: ${{ secrets.CSV_URL }}
        run: python scripts/snapshot.py

      - name: Commit & push if changed
        run: |
          if git diff --quiet docs/; then
            echo "No changes in docs/*"
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/snapshot.json docs/changes.json
            git commit -m "Update snapshot & changes [skip ci]"
            git push
          fi

      # opzionale: invia alert Telegram se ci sono cambi
      - name: Notify Telegram on changes
        if: always()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          if [ -n "$TELEGRAM_BOT_TOKEN" ] && [ -n "$TELEGRAM_CHAT_ID" ]; then
            CHANGES=$(jq '.changes | length' docs/changes.json)
            if [ "$CHANGES" -gt 0 ]; then
              TEXT=$(jq -r '
                .changes[0:10] | map("*\(.key)*: \(.type) | from: \(.from) -> to: \(.to)") | join("\n")
              ' docs/changes.json)
              MSG="🚨 *Crypto changes:* ${CHANGES} updates\n${TEXT}"
              curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
                   -d chat_id="${TELEGRAM_CHAT_ID}" -d parse_mode=Markdown -d text="$MSG" >/dev/null
              echo "Telegram alert sent."
            else
              echo "No changes; no alert."
            fi
          else
            echo "Telegram secrets not set; skipping alert."
          fi
